xb1/xb1/shop/urls.py
from django.conf.urls import url

from . import views

app_name = 'shop'
urlpatterns = [
    url(r'^$', views.ShopIndex.as_view(), name='shopView'),

    # By PK of Item
    url(r'^cart/insert/(?P<pk>[0-9]+)$', views.CartInsertItemView.as_view(), name="cartinsert"),

    # By PK of CartEntry 
    url(r'^cart/update/(?P<pk>[0-9]+)/add$', views.CartAddItemView.as_view(), name="cartadd"),
    url(r'^cart/update/(?P<pk>[0-9]+)/remove$', views.CartRemoveItemView.as_view(), name="cartremove"),
    url(r'^cart/update/(?P<pk>[0-9]+)/discard$', views.CartDiscardItemView.as_view(), name="cartdiscard"),
    url(r'^cart/update/discard', views.CartDiscardItemView.as_view(), name="cartdiscardall"),
    url(r'^cart/update/(?P<pk>[0-9]+)/set/(?P<spec>[0-9]+)', views.CartSetSpecificationView.as_view(), name="cartspecificationset"),

    url(r'^admin/item/list$', views.ItemListView.as_view(), name="adminItemList"),
    url(r'^admin/item/create$', views.ItemCreateView.as_view(), name="adminItemCreate"),
    url(r'^admin/item/create/(?P<pk>[0-9]+)$', views.ItemCreateAsView.as_view(), name="adminItemCreateAs"),
    url(r'^admin/item/delete/(?P<pk>[0-9]+)$', views.ItemDeleteView.as_view(), name="adminItemDelete"),
    url(r'^admin/item/detail/(?P<pk>[0-9]+)$', views.ItemDetailView.as_view(), name="adminItemDetail"),
    url(r'^admin/item/update/(?P<pk>[0-9]+)$', views.ItemUpdateView.as_view(), name="adminItemUpdate"),
    url(r'^admin/item/deactivate/(?P<pk>[0-9]+)$', views.ItemDeactivateView.as_view(), name="adminItemDeactivate"),


    url(r'^order/create$', views.OrderCreateView.as_view(), name="orderCreate"),
    url(r'^order/tracker/(?P<slug>[\w-]+)/$', views.OrderTrackerView.as_view(), name="orderTracker"),

    url(r'^user/order/list$', views.OrderListUserView.as_view(), name="userOrderList"),

    url(r'^admin/order/list$', views.OrderListView.as_view(), name="adminOrderList"),
    url(r'^admin/order/payment/confirm/(?P<pk>[0-9]+)$', views.OrderPaymentConfirmView.as_view(), name="adminOrderPaymentConfirm"),
    url(r'^admin/order/payment/revoke/(?P<pk>[0-9]+)$', views.OrderPaymentRevokeView.as_view(), name="adminOrderPaymentRevoke"),
    url(r'^admin/order/detail/(?P<pk>[0-9]+)$', views.OrderDetailView.as_view(), name="adminOrderDetail"),
]

xb1/xb1/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import activate_registration, PasswordChangeView, EmailChangeView, activate_email, CKEditorBrowseView, CKEditorUploadView, CKEditorDeleteView
from django.contrib.auth import views as auth_views

admin.autodiscover()

urlpatterns = [
    # Index
    url(r'^$', views.IndexView.as_view(), name='index'),

    # Admin urls
    url(r'^users/$', views.UserListView.as_view(), name='user_list'),
    url(r'^users/user_detail/(?P<pk>\d+)/$', views.UserDetailView.as_view(), name='user_detail'),
    url(r'^users/user_detail/(?P<pk>\d+)/comments/$', views.UserCommentsView.as_view(), name='user_comments'),

    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^admin_tools/ ', include('admin_tools.urls')),

    # Login redirect urls
    url(r'^D7E88079F0C53EE2AC930A3D7300218AC6F0615FECD4A91CFDBA/$', views.LoginViewModal.as_view(), name='login_modal'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),

    # Password reset urls
    url(r'^password_reset/$', views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^password_reset_complete/$', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # Profile view
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),

    # Register
    url(r'^register/', views.Register.as_view(), name='register'),

    # Apps.
    url(r"^articles/", include("xb1.articles.urls")),
    url(r"^core/", include("xb1.core.urls")),
    url(r"^contact/", include("xb1.contact.urls")),
    url(r"^forum/", include("xb1.forum.urls")),
    url(r"^eshop/", include("xb1.eshop.urls")),
    url(r"^shop/", include("xb1.shop.urls")),

    url(r"^sent/", views.ActivationSentView.as_view(), name="activation_sent"),
    path('activate_registration/<slug:uidb64>/<slug:token>/', activate_registration, name='activate_registration'),

    url(r'^profile/change_password/', PasswordChangeView.as_view(), name='change_password'),
    url(r'^profile/change_email/', EmailChangeView.as_view(), name='change_email'),
    path('activate_email/<slug:uidb64>/<slug:token>/', activate_email, name='activate_email'),

    # CKEDITOR
    # url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^ckeditor/upload/', CKEditorUploadView.as_view(), name='ckeditor_upload'),
    url(r'^ckeditor/browse/', CKEditorBrowseView.as_view(), name='ckeditor_browse'),
    url(r'^ckeditor/delete/', CKEditorDeleteView.as_view(), name='ckeditor_delete'),

    path('captcha/', include('captcha.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

xb1/xb1/shop/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib import messages

from ..core.widgets import DatePickerInput
from .models import Item, Order

class ItemCreateForm(forms.ModelForm):
    price = forms.FloatField(label=_("Product price"))
    till = forms.DateTimeField(label=_("Till"))
    specificationname = forms.CharField(label=_("Specification name"), max_length = 50,required=False)
    specificationvalue = forms.CharField(label=_("Specification value"), max_length = 50,required=False)

    def __init__(self, *args, **kwargs):
        super(ItemCreateForm, self).__init__(*args, **kwargs)
        self.fields['till'].widget = DatePickerInput(attrs={'autocomplete':'off'})

    class Meta:
        model = Item
        fields = ("name", "desc", "image")
        widgets = {
            'image': forms.FileInput
        }

class ItemUpdateForm(forms.ModelForm):
    price = forms.FloatField(label=_("Product price"))
    till = forms.DateTimeField(label=_("Till"))
    specificationname = forms.CharField(label=_("Specification name"), max_length = 50,required=False)
    specificationvalue = forms.CharField(label=_("Specification value"), max_length = 50,required=False)

    def clean(self):
        return super(ItemUpdateForm, self).clean()

    def __init__(self, *args, **kwargs):
        super(ItemUpdateForm, self).__init__(*args, **kwargs)
        self.fields['till'].widget = DatePickerInput(attrs={'autocomplete':'off'})

    class Meta:
        model = Item
        fields = ("name", "desc", "image")
        widgets = {
            'image': forms.FileInput
        }

class OrderCreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(OrderCreateForm, self).__init__(*args, **kwargs)

        for field_name in ("firstname", "lastname", "email", "city", "street", "post", "phone"):
            self.fields[field_name].widget.attrs['class'] = 'order_form_input'

    def clean(self):

        cleaned_data = super(OrderCreateForm, self).clean()
        
        for field_name in ("firstname", "lastname", "email", "city", "street", "post", "phone"):
            if not cleaned_data[field_name]:
                self.add_error(field_name, _("Empty value is not allowed"))
                self.fields[field_name].widget.attrs['style'] = 'border-color: red'

        return cleaned_data

    class Meta:
        model = Order
        fields = ("firstname", "lastname", "email", "city", "street", "post", "phone")
        labels = {
            'post': _("Postal code"),
        }

xb1/xb1/shop/views.py
from django.shortcuts import render
from django.contrib import messages
from django.views.generic import ListView
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.edit import FormView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from django.views.generic.base import RedirectView
from django.views.generic.detail import DetailView
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.urls import reverse
from django.shortcuts import redirect
from django.core import serializers
from django.utils import timezone
from django.db import transaction
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMultiAlternatives

from ..core.views import LoginMixinView
from .models import Item, Price, CartEntry, Specification, SpecificationEntry, Order, Payment
from .cart import Cart
from .forms import ItemCreateForm, ItemUpdateForm, OrderCreateForm
from ..settings import EMAIL_HOST_USER, ESHOP_BANK_ACCOUNT

import datetime
import random

class ShopIndex(LoginMixinView, ListView):

    model = Item
    template_name = "shop.html"

    def get_context_data(self, **kwargs):
        context = super(ShopIndex, self).get_context_data(**kwargs)
        context["cart"] = Cart(self.request)

        return context

class CartInsertItemView(RedirectView):

    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        if kwargs.get('pk', None) is None:
            messages.warning(self.request, _("Unknown key"))
            return reverse_lazy("shop:shopView")

        item = Item.objects.filter(pk = kwargs.get('pk')).first()
        if not item:
            messages.warning(self.request, _("Not found"))
            return reverse_lazy("shop:shopView")

        cart = Cart(self.request)
        cart.insert(item)

        messages.success(self.request, _('Cart was updated.'))
        return reverse_lazy("shop:shopView")

class CartAddItemView(RedirectView):

    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        if kwargs.get('pk', None) is None:
            messages.warning(self.request, _("Unknown key"))
            return reverse_lazy("shop:shopView")

        entry = CartEntry.objects.filter(pk = kwargs.get('pk')).first()
        if not entry:
            messages.warning(self.request, _("Not found"))
            return reverse_lazy("shop:shopView")

        cart = Cart(self.request)
        cart.add(entry.pk, 1)

        messages.success(self.request, _('Cart was updated.'))
        return reverse_lazy("shop:shopView")

class CartRemoveItemView(RedirectView):

    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        if kwargs.get('pk', None) is None:
            messages.warning(self.request, _("Unknown key"))
            return reverse_lazy("shop:shopView")

        entry = CartEntry.objects.filter(pk = kwargs.get('pk')).first()
        if not entry:
            messages.warning(self.request, _("Not found"))
            return reverse_lazy("shop:shopView")

        cart = Cart(self.request)
        cart.remove(entry.pk, 1)

        messages.success(self.request, _('Cart was updated.'))
        return reverse_lazy("shop:shopView")

class CartDiscardItemView(RedirectView):

    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        if kwargs.get('pk', None) is None:
            cart = Cart(self.request)
            cart.discard(None)

        else:
            entry = CartEntry.objects.filter(pk = kwargs.get('pk')).first()
            if not entry:
                messages.warning(self.request, _("Not found"))
                return reverse_lazy("shop:shopView")

            cart = Cart(self.request)
            cart.discard(entry.pk)

        messages.success(self.request, _('Cart was updated.'))
        return reverse_lazy("shop:shopView")

class CartSetSpecificationView(RedirectView):

    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        if kwargs.get('pk', None) is None or kwargs.get('spec', None) is None:
            messages.warning(self.request, _("Unknown key"))
            return reverse_lazy("shop:shopView")

        entry = CartEntry.objects.filter(pk = kwargs.get('pk')).first()
        if not entry:
            messages.warning(self.request, _("Not found"))
            return reverse_lazy("shop:shopView")

        specentry = SpecificationEntry.objects.filter(pk = kwargs.get('spec')).first()  
        if not specentry:
            messages.warning(self.request, _("Not found"))
            return reverse_lazy("shop:shopView")

        if specentry.specification.active is False:
            messages.warning(self.request, _("Not active"))
            return reverse_lazy("shop:shopView")

        if specentry.specification.item.pk is not entry.item.pk:
            messages.warning(self.request, _("Not related specification"))
            return reverse_lazy("shop:shopView") 

        cart = Cart(self.request)
        cart.spec(entry.pk, specentry.pk)  

        messages.success(self.request, _('Cart was updated.'))
        return reverse_lazy("shop:shopView")       

class ItemListView(LoginMixinView, LoginRequiredMixin, PermissionRequiredMixin, ListView):

    model = Item
    template_name = "adminItemList.html"
    permission_required = "shop.view_item"

class ItemDetailView(LoginMixinView, LoginRequiredMixin, PermissionRequiredMixin, DetailView):

    model = Item
    template_name = "adminItemDetail.html"
    permission_required = "shop.view_item"

    def get_context_data(self, *args, **kwargs):
        context = super(ItemDetailView, self).get_context_data(*args, **kwargs)
        context['priceHistory'] = Price.objects.filter(item=context['item']).order_by('till')

        return context

class ItemDeactivateView(LoginMixinView, LoginRequiredMixin, PermissionRequiredMixin, RedirectView):

    permanent = False
    permission_required = "shop.change_item"

    def get_redirect_url(self, *args, **kwargs):
        if kwargs.get('pk', None) is None:
            messages.warning(self.request, _("Unknown key"))
            return reverse_lazy("shop:adminItemList")

        item = Item.objects.filter(pk = kwargs.get('pk')).first()
        if not item:
            messages.warning(self.request, _("Not found"))
            return reverse_lazy("shop:adminItemList")

        price = item.price
        price.till = timezone.now()
        price.save()

        messages.success(self.request, _('Item deactivated'))
        return reverse_lazy("shop:adminItemList")

class ItemDeleteView(LoginMixinView, LoginRequiredMixin, PermissionRequiredMixin, RedirectView):

    permanent = False
    permission_required = "shop.delete_item"

    def get_redirect_url(self, *args, **kwargs):
        if kwargs.get('pk', None) is None:
            messages.warning(self.request, _("Unknown key"))
            return reverse_lazy("shop:adminItemList")

        item = Item.objects.filter(pk = kwargs.get('pk')).first()
        if not item:
            messages.warning(self.request, _("Not found"))
            return reverse_lazy("shop:adminItemList")

        if item.price:
            messages.warning(self.request, _("Can not delete active items"))
            return reverse_lazy("shop:adminItemList")

        item.delete()
        messages.success(self.request, _('Item deleted'))
        return reverse_lazy("shop:adminItemList")

class ItemCreateView(LoginMixinView, LoginRequiredMixin, PermissionRequiredMixin, FormView):

    form_class = ItemCreateForm
    template_name = "adminItemCreate.html"
    success_url = reverse_lazy("shop:adminItemList")
    permission_required = "shop.add_item"

    def form_valid(self, form):
        item = Item.objects.create(name=form.cleaned_data['name'], desc=form.cleaned_data['desc'], image=form.cleaned_data['image'])
        Price.objects.create(price=form.cleaned_data['price'], item=item, since=timezone.now(), till=form.cleaned_data['till'])

        if form.cleaned_data['specificationname'] != '' and form.cleaned_data['specificationvalue'] != '':
            specification = Specification.objects.create(name=form.cleaned_data['specificationname'], item=item, active=True)
            entries = form.cleaned_data['specificationvalue'].split(',')
            for entry in entries:
                SpecificationEntry.objects.create(value=entry, specification=specification)

        return super().form_valid(form)

class ItemUpdateView(LoginMixinView, LoginRequiredMixin, PermissionRequiredMixin, UpdateView):

    model = Item
    form_class = ItemUpdateForm
    template_name = "adminItemUpdate.html"
    success_url = reverse_lazy("shop:adminItemList")
    permission_required = "shop.change_item"

    def get_initial(self):
        initial = super(ItemUpdateView, self).get_initial()
        if self.object.price is not None:
            initial['price'] = self.object.price.price
            initial['till'] = self.object.price.till

        if self.object.specification is not None:
            initial['specificationname'] = self.object.specification.name
            initial['specificationvalue'] = ",".join(entry.value for entry in self.object.specification.entry)
                
        return initial

    def form_valid(self, form):
        if self.object.specification is not None:
            spec = self.object.specification
            spec.active=False
            spec.save()

        if form.cleaned_data['specificationname'] != '' and form.cleaned_data['specificationvalue'] != '':
            specification = Specification.objects.create(name=form.cleaned_data['specificationname'], item=self.object, active=True)

xb1/xb1/shop/templates/adminItemList.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}

{%block include%}
	<link rel="stylesheet" href="{% static 'css/product_list.css' %}" >
{%endblock%}

{%block content %}
	{% if object_list %}
		<div id="product-list">
			<div class="responsive-table-wrapper">
				<table>
					<thead>
						<tr>
							<th>{% trans "Name" %}</th>
							<th>{% trans "Price" %}</th>
							<th>{% trans "Image" %}</th>
							<th>{% trans "Description" %}</th>
							<th>{% trans "Active" %}</th>
							<th colspan="4">{% trans "Action" %}</th>
						</tr>
					</thead>
					<tbody>
						{% for item in object_list %}
						<tr>
							<td>{{ item.name }}</td>
							<td>{{ item.price.price }}</td>
							<td><a href="{{ item.image.url }}"><img class=productImg src="{{ item.image.url }}"></a></td>
							<td>{{ item.desc }}</td>
							{% if item.price %}
								<td><i class="success-green fas fa-check"></i></td>
							{% else %}
								<td><i class="error-red fa fa-times"></i></td>
							{% endif %}
							<td><a href="{% url 'shop:adminItemDetail' pk=item.pk %}"><i class="fas fa-info"></i> {% trans "Detail" %}</a></td>
							<td><a href="{% url 'shop:adminItemUpdate' pk=item.pk %}"><i class="fas fa-edit"></i> {% trans "Edit" %}</a></td>
							{% if item.price %}
								<td><a href="{% url 'shop:adminItemDeactivate' pk=item.pk %}"><i class="fas fa-power-off"></i> {% trans "Deactivate" %}</a></td>
							{% else %}
								<td><a href="{% url 'shop:adminItemDelete' pk=item.pk %}"><i class="far fa-trash-alt"></i> {% trans "Delete" %}</a></td>
							{% endif %}
							<td><a href="{% url 'shop:adminItemCreateAs' pk=item.pk %}"><i class="far fa-plus-square"></i> {% trans "Create" %}</a></td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	{% endif %}
{% endblock %}

xb1/xb1/shop/templates/shop.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block include %}
<link rel="stylesheet" href="{% static 'css/layout_shopIndex.css' %}" >
<link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}" />
{% endblock %}

{% block content %}
<div class="eshop_topnav">
	{% if perms.shop.add_item %}
	<div>
		<a class="add_product_button" href="{% url 'shop:adminItemCreate' %}">{% trans "New product" %}<i class="fas fa-plus"></i></a>
	</div>
	{% endif %}
	{% if perms.shop.view_item %}
	<div>
		<a class="view_products_button" href="{% url 'shop:adminItemList' %}">{% trans "Show products list" %}<i class="fas fa-list"></i></a>
	</div>
	{% endif %}
</div>

<div class="shopOrderBox">

	<div class="cart_header">
		<button class="cart_caption"><i class="fas fa-shopping-cart"></i> {% trans "Cart" %} ({{ cart.count }}) <i class="cart_display_arrow fas"></i></button>
	</div>

	<div class="collapsible_cart">
		<div class="collapsible_cart_wrapper">
			{% if cart.count == 0 %}
				<div class="empty_cart">{% trans "Cart is empty" %}</div>
			{% else %}
				<table class = "cartTable" cellspacing="0" cellpadding="0">
					<tr class="cartTableRow">
						<th class="cartTableCol" colspan="2">{% trans "Product" %}</th>
						<th class="cartTableCol" colspan="2">{% trans "Specification" %}</th>
						<th class="cartTableCol">{% trans "Amount" %}</th>
						<th class="cartTableCol">{% trans "Price" %}</th>
						<th class="cartTableCol">{% trans "Add" %}</th>
						<th class="cartTableCol">{% trans "Remove" %}</th>
						<th class="cartTableCol">{% trans "Cancel" %}</th>
					</tr>
				{% for item in cart %}
					<tr class="cartTableRow">
						<td class="cartTableColMerge">
							<img class=shopOfferImageCart src="{{ item.item.image.url }}">
						</td>
						<td class="cartTableColMerge"> {{ item.item.name }} </td>
						<td class="cartTableColMerge" style="text-align: center;">{{ item.item.specification.name}}</td>
						<td class="cartTableColMerge" style="text-align: center">
							{% if item.item.specification %}
								<div class="dropdown">
									<div class="dropbtn">{{ item.specification.value }}  <i class="fas fa-angle-down"></i></div>
									<div class="dropdown-content">
										{% for specentry in item.item.specification.entry %}
											{% if specentry.value != item.specification.value %}
												<a href="{% url 'shop:cartspecificationset' pk=item.pk spec=specentry.pk %}">{{ specentry.value }}</a>
											{% endif %}
										{% endfor %}
									</div>
								</div>
							{% endif %}
						</td>

						<td class="cartTableCol"> {{ item.count }}  </td>
						<td class="cartTableCol"> {{ item.price.price|floatformat:"-2" }} </td>
						<td class="cartTableCol"><a href="{% url 'shop:cartadd' pk=item.pk %}"><i class="fas fa-plus"></i></a> </td>
						<td class="cartTableCol"><a href="{% url 'shop:cartremove' pk=item.pk %}"><i class="fas fa-minus"></i></a></td>
						<td class="cartTableCol"><a href="{% url 'shop:cartdiscard' pk=item.pk %}"><i class="fas fa-times"></i></a></td>
					</tr>
				{% endfor %}
			</table>
			<br>
			<a href="{% url 'shop:cartdiscardall' %}"><i class="fas fa-trash"></i> {% trans "Delete all" %}</a> <br>
			<div class="cartBottom">
				Celková cena: {{ cart.price|floatformat:"-2" }} <br>
				<a href="{% url 'shop:orderCreate' %}" class="order_btn">{% trans 'Create order' %}</a>
			</div>
			{% endif %}
		</div>
	</div>
</div>

<div class="shopItemBox">
	<ul>
		{% for item in object_list %}
			{% if item.price %}
			<li>
				<div class="shopOfferItem">
					<div class="shopOfferImage">
						<img class=shopOfferImage src="{{ item.image.url }}">
					</div>
					<div class="shopOfferText">
						<span class="shopOfferName">{{ item.name }}</span>
						<div class="shopOfferDesc">{{ item.desc }}</div>
					</div>
					<div class="shopOfferControl">
						<div>{{ item.price.price|floatformat:"-2" }}</div>
						<div><a onclick="sessionStorage.setItem('cartStatus', 'opened');" href="{% url 'shop:cartinsert' pk=item.pk %}">{% trans "Add to cart" %}</a></div>
					</div>
				</div>
			</li>
			{% endif %}
		{% endfor %}
	</ul>
</div>

<script>
	$("#specification-select").on('change', function() {
		window.location.href = this.value;
	});

	$(".collapsible_cart").css("transition",  'none')
	if(sessionStorage.getItem('cartStatus') == "opened") {
		$(".cart_caption .cart_display_arrow").addClass('fa-angle-up')
		$(".collapsible_cart").css("max-height", $(".collapsible_cart_wrapper").height() + 'px')
    } else if(sessionStorage.getItem('cartStatus') == "collapsed"){
		$(".cart_caption .cart_display_arrow").addClass('fa-angle-down')
		$(".cart_caption").addClass('cart-collapsed')
    } else {
		sessionStorage.setItem('cartStatus', 'collapsed');
		$(".cart_caption .cart_display_arrow").addClass('fa-angle-down')
		$(".cart_caption").addClass('cart-collapsed')
		$(".collapsible_cart").css("max-height", '0px')
	}


	$(".cart_caption").click(function(event){
		$(this).toggleClass('cart-collapsed')
		$(this).find(".cart_display_arrow").removeClass('fa-angle-down fa-angle-up')

		if($(this).hasClass('cart-collapsed')) {
			sessionStorage.setItem('cartStatus', 'collapsed');
			$(this).find(".cart_display_arrow").addClass('fa-angle-down')
			$(".collapsible_cart").css("max-height", '0px')
		}else {
			sessionStorage.setItem('cartStatus', 'opened');
			$(this).find(".cart_display_arrow").addClass('fa-angle-up')
			$(".collapsible_cart").css("max-height", $(".collapsible_cart_wrapper").height() + 'px')
		}
	});
</script>
{% endblock %}

xb1/xb1/shop/templates/userOrderList.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}

{%block include%}
<link rel="stylesheet" href="{% static 'css/orders_list.css' %}">
<script defer src="{% static 'js/orders_list.js' %}"></script>
{%endblock%}

{%block content %}

{% if object_list %}
<div id="orders-list">
	<div class="responsive-table-wrapper">
		<table>
			<thead>
				<tr>
					<th>{% trans "First Name" %}</th>
					<th>{% trans "Last Name" %}</th>
					<th>{% trans "Email" %}</th>
					<th>{% trans "VS" %}</th>
					<th>{% trans "TotalPrice" %}</th>
					<th>{% trans "Payed" %}</th>
					<th>{% trans "Detail" %}</th>
				</tr>
			</thead>
			<tbody>
				{% for order in object_list %}
				<tr>
					<td>{{ order.firstname }}</td>
					<td>{{ order.lastname }}</td>
					<td class="order-email">{{ order.email }}</td>
					<td>{{ order.payment.variableSymbol }}</td>
					<td>{{ order.cart.total }},-</td>
					{% if order.payment.received %}
						<td><i class="success-green fas fa-check"></i></td>
					{% else %}
						<td><i class="error-red fa fa-times"></i></td>
					{% endif %}
					<td><a href="{% url 'shop:orderTracker' slug=order.slug %}"><i class="fas fa-info"></i> {% trans "Detail" %}</a></td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>
{% endif %}

{% endblock %}


{% block modal %}
<h1>{% trans "Delete order" %}</h1>
<p>{% trans "Are you sure you want to delete order with email address:" %} <strong></strong>?</p>
<p>{% trans "This action can't be undone!" %}</p>

<form action="" method="POST">
	{% csrf_token %}
	<button>{% trans "Confirm" %}</button>
</form>
{% endblock %}