xb1/xb1/articles/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'articles'
urlpatterns = [

    # Articles
    url(r'^$', views.ArticleListView.as_view(), name="article_list"),
    url(r'^create/$', views.ArticleCreateView.as_view(), name="article_create"),
    url(r'^(?P<pk>\d+)/', views.ArticleUpdateView.as_view(), name="article_update"),
    url(r'^(?P<slug>[\w-]+)/$', views.ArticleDetailView.as_view(), name="detail"),
    url(r'^get_articles_by_category', views.GetArticlesByCategoryView.as_view(), name="get_articles_by_category"),
    url(r'^get_all_articles', views.GetAllArticlesView.as_view(), name="get_all_articles"),
    url(r'^search_articles', views.ArticleSearchView.as_view(), name="search_articles"),
    url(r'^article_delete', views.ArticleDeleteView.as_view(), name="article_delete"),
    url(r'^hide_article', views.HideArticleView.as_view(), name="hide_article"),
    url(r'^publish_article', views.PublishArticleView.as_view(), name="publish_article"),

    # Comments
    url(r'^post_comment', login_required(views.PostCommentView.as_view()), name="post_comment"),
    url(r'^comment/(?P<pk>\d+)/ban', views.BanCommentView.as_view(), name="ban_comment"),
    url(r'^comment/(?P<pk>\d+)/unban', views.UnbanCommentView.as_view(), name="unban_comment"),

    # Tags
    url(r'^create_tag', views.TagCreateView.as_view(), name="create_tag"),

    # Categories
    url(r'^create_category', views.CategoryCreateView.as_view(), name="create_category"),
    url(r'^delete_category', views.CategoryDeleteView.as_view(), name="delete_category"),


]

xb1/xb1/forum/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'forum'
urlpatterns = [

    # Forum
    url(r'^$', views.ForumIndexView.as_view(), name="index"),
    url(r'^category/(?P<pk>\d+)/$', views.ForumListView.as_view(), name="forum_list"),
    url(r'^category/$', views.ForumListView.as_view(), name="forum_list"),
    url(r'^forum-category-create/$', views.ForumCategoryCreateView.as_view(), name="create_forum_category"),
    url(r'^forum-category-update/(?P<pk>\d+)/$', views.ForumCategoryUpdateView.as_view(), name="update_forum_category"),
    url(r'^forum-category-delete/(?P<pk>\d+)/$', views.ForumCategoryDeleteView.as_view(), name="delete_forum_category"),
    url(r'^forum-detail/(?P<pk>\d+)/$', views.ForumDetailView.as_view(), name="forum_detail"),
    url(r'^forum-category/(?P<pk>\d+)/create-forum/$', views.ForumCreateView.as_view(), name="create_forum"),
    url(r'^forum-delete/(?P<pk>\d+)/$', views.ForumDeleteView.as_view(), name="delete_forum"),

    url(r'^post-comment', login_required(views.PostCommentView.as_view()), name="post_comment"),
]

xb1/xb1/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import activate_registration, PasswordChangeView, EmailChangeView, activate_email, CKEditorBrowseView, CKEditorUploadView, CKEditorDeleteView
from django.contrib.auth import views as auth_views

admin.autodiscover()

urlpatterns = [
    # Index
    url(r'^$', views.IndexView.as_view(), name='index'),

    # Admin urls
    url(r'^users/$', views.UserListView.as_view(), name='user_list'),
    url(r'^users/user_detail/(?P<pk>\d+)/$', views.UserDetailView.as_view(), name='user_detail'),
    url(r'^users/user_detail/(?P<pk>\d+)/comments/$', views.UserCommentsView.as_view(), name='user_comments'),

    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^admin_tools/ ', include('admin_tools.urls')),

    # Login redirect urls
    url(r'^D7E88079F0C53EE2AC930A3D7300218AC6F0615FECD4A91CFDBA/$', views.LoginViewModal.as_view(), name='login_modal'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),

    # Password reset urls
    url(r'^password_reset/$', views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^password_reset_complete/$', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # Profile view
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),

    # Register
    url(r'^register/', views.Register.as_view(), name='register'),

    # Apps.
    url(r"^articles/", include("xb1.articles.urls")),
    url(r"^core/", include("xb1.core.urls")),
    url(r"^contact/", include("xb1.contact.urls")),
    url(r"^forum/", include("xb1.forum.urls")),
    url(r"^eshop/", include("xb1.eshop.urls")),
    url(r"^shop/", include("xb1.shop.urls")),

    url(r"^sent/", views.ActivationSentView.as_view(), name="activation_sent"),
    path('activate_registration/<slug:uidb64>/<slug:token>/', activate_registration, name='activate_registration'),

    url(r'^profile/change_password/', PasswordChangeView.as_view(), name='change_password'),
    url(r'^profile/change_email/', EmailChangeView.as_view(), name='change_email'),
    path('activate_email/<slug:uidb64>/<slug:token>/', activate_email, name='activate_email'),

    # CKEDITOR
    # url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^ckeditor/upload/', CKEditorUploadView.as_view(), name='ckeditor_upload'),
    url(r'^ckeditor/browse/', CKEditorBrowseView.as_view(), name='ckeditor_browse'),
    url(r'^ckeditor/delete/', CKEditorDeleteView.as_view(), name='ckeditor_delete'),

    path('captcha/', include('captcha.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

xb1/xb1/articles/models.py
from django.db import models
from model_utils.models import TimeStampedModel
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from os.path import basename, splitext
from django.utils.text import slugify


from ..core.models import User, DeleteMixin

import random

class Category(DeleteMixin):
    """
    Category model for filtering articles.
    """

    name = models.CharField(_("Name"), max_length=100)

    def __str__(self):
        return self.name


class Tag(DeleteMixin):
    """
    Category tags model for filtering articles.
    """

    name = models.CharField(_("Name"), max_length=100)

    def __str__(self):
        return self.name


class UploadedFile(models.Model):
    """
    CKEditor model for storing uploaded files.
    """

    uploaded_file = models.FileField(upload_to=u"article_content_images/")
    uploaded_at = models.DateField(editable=False, auto_now_add=True)

    def __str__(self):
        return basename(self.uploaded_file.path)

    def url(self):
        return self.uploaded_file.url

    def delete(self, *args, **kwargs):
        file_storage, file_path = self.uploaded_file.storage, self.uploaded_file.path
        super(UploadedFile, self).delete(*args, **kwargs)
        name, ext = splitext(file_path)
        file_storage.delete(file_path)
        file_storage.delete(name + "_thumb" + ext)

class Article(TimeStampedModel, DeleteMixin):

    HIDDEN = 0
    PUBLISHED = 1
    STATE_CHOICES = (
        (HIDDEN, _("Hidden")),
        (PUBLISHED, _("Published"))
    )

    title          = models.CharField(verbose_name=_("Title"), max_length=100)
    thumbnail      = models.ImageField(verbose_name=_("Thumbnail"), null=True, blank=True, upload_to='thumbnails')
    preview_text   = models.TextField(verbose_name=_("Preview text"), blank=True, null=False, default=_("Read more..."))
    author         = models.ForeignKey(User, verbose_name=_("Author"), on_delete=models.SET_NULL, blank=True, null=True)
    slug           = models.SlugField(verbose_name=_("Slug"), unique=True, max_length=100, blank=True, null=True)
    category       = models.ManyToManyField(Category, verbose_name=_("Category"), blank=True)
    tags           = models.ManyToManyField(Tag, verbose_name=_("Tag"), blank=True)
    allow_comments = models.BooleanField(verbose_name=_("Comments allowed"), default=True)
    published_from = models.DateTimeField(verbose_name=_("Published from"), default=timezone.now, null=True, blank=True)
    published_to   = models.DateTimeField(verbose_name=_("Published to"), null=True, blank=True)
    text           = RichTextField(verbose_name=_("Text"), blank=True, null=True)
    sources        = models.TextField(verbose_name=_("Sources"), blank=True, null=True)
    article_state  = models.PositiveSmallIntegerField(verbose_name=_("State"), choices=STATE_CHOICES, default=HIDDEN)

    def save(self, *args, **kwargs):
        if self.slug is None:
            self._generate_slug()

        super().save(*args, **kwargs)

    def _generate_slug(self):

        slg = slugify(self.title)

        # Test if slug exists
        while Article.objects.filter(slug=slg).exists():
            slg = slg + "_" + str(random.randint(0, 1000))

        self.slug = slg


class ForumCategory(DeleteMixin):

    title = models.CharField(verbose_name=_("Title"), max_length=100)
    is_open = models.BooleanField(verbose_name=_("Is public"), default=True)
    description = models.TextField(verbose_name=_("Category description"), blank=True, null=True)

    def __str__(self):
        return self.title


class Forum(TimeStampedModel, DeleteMixin):

    title = models.CharField(verbose_name=_("Title"), max_length=100)
    description = models.TextField(verbose_name=_("Forum description"), blank=True, null=True)
    author = models.ForeignKey(User, verbose_name=_("Author"), on_delete=models.SET_NULL, blank=True, null=True)
    is_closed = models.BooleanField(verbose_name=_("Is closed"), default=False)
    category = models.ForeignKey(ForumCategory, verbose_name=_("Category"), on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title


class Comment(TimeStampedModel, DeleteMixin):

    article = models.ForeignKey(Article, verbose_name=_("Article"), on_delete=models.CASCADE, blank=True, null=True)
    forum = models.ForeignKey(Forum, verbose_name=_("Forum"), on_delete=models.CASCADE, blank=True, null=True)
    reaction_to = models.ForeignKey("Comment", verbose_name=_("Reacts to"), on_delete=models.CASCADE, blank=True, null=True)
    author = models.ForeignKey(User, verbose_name=_("Author"), on_delete=models.SET_NULL, blank=True, null=True)
    text = RichTextField(verbose_name=_("Text"), blank=True, null=True, config_name="comment")
    is_censured = models.BooleanField(verbose_name=_("Is censured"), default=False)
    date = models.DateTimeField(verbose_name=_("Posted on"), default=timezone.now, null=False, blank=False, editable=False)

    def __str__(self):
        return self.text if self.text else "---"

xb1/xb1/forum/templates/forum_category_form.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block include %}
<link rel="stylesheet" href="{% static 'css/forum_form.css' %}" >
{% endblock %}

{% block content %}
<form id ="article_form" method="post" enctype="multipart/form-data">{% csrf_token %}
        <div style="width: 80%; margin: 0 auto;">

        {% for field in form.visible_fields %}
            {% if field == form.is_open %}
            {{ field.label_tag }}
            {{ field }}<br>
            <br>
            {%else%}
            {{ field.label_tag }}
            {{ field }}
            {% endif %}
        {% endfor %}
    </div>

    <button class="article_form_btn" type="submit">{% trans 'Submit' %}</button>
</form>
{% endblock %}

xb1/xb1/forum/templates/forum_comment.html
{% load i18n %}
{% for comment in comments %}
    <li>

        <div class="comment">
            <img class=comment_profile_pic src="{{comment.author.profile.image.url}}">
            <div class="comment_content">
                <div class= "comment_header">
                    <div class="comment_nickname">{{comment.author.profile.nickname}}</div>
                    <div class="comment_date">{{comment.date}}</div>
                </div>

                {% if comment.is_censured %}
                    <div class="comment_text">
                        <b>{% trans "Comment has been banned for inappropriate speech." %}</b>
                    </div>
                {% else %}
                    <div class="comment_text">{{ comment.text }}</div>
                {% endif %}

            </div>
            {% if user.is_authenticated %}

                <div class="comment_reply_form_wrapper">

                    <!-- Admin section for banning -->
                    {% if perms.articles.change_comment %}
                        {% if not comment.is_censured %}
                            <a href="{% url 'articles:ban_comment' pk=comment.id %}">
                                <button class="comment_section_button">
                                    {% trans "Censure" %}<i class="fas fa-ban" style="font-size: 15px;"></i>
                                </button>
                            </a>
                        {% else %}
                            <a href="{% url 'articles:unban_comment' pk=comment.id %}">
                                <button class="comment_section_button">
                                    {% trans "Un-censure" %}<i class="fas fa-lock-open" style="font-size: 15px;"></i>
                                </button>
                            </a>
                            <div class="comment_text">
                                {% trans "Banned text:" %}{{comment.text }}
                            </div>
                        {% endif %}
                    {% endif %}

                    <button class="comment_section_button" id="button_comment_{{comment.id}}" onclick="showReply('comment_{{comment.id}}')">
                        Reply
                    </button>
                    <div id="comment_{{comment.id}}" style="display: none" >
                        <form id="{{comment.id}}" class="comment_reply_form" method="POST">
                            {% csrf_token %}
                            <textarea required rows=1 placeholder="Add a reply"></textarea>
                            <button class="comment_section_button">Reply</button>
                        </form>
                    </div>
                    <script>
                        function showReply(comment_id) {
                            var x = document.getElementById(comment_id);
                            x.style.display = "block";
                            var y = document.getElementById("button_" + comment_id);
                            y.style.display = "none";
                        }
                    </script>
                </div>
            {% endif %}
        </div>

        <div class="subcomments">
            <ul>
                {% if comment.comments|length %}
                    {% include "forum_comment.html" with comments=comment.comments %}
                {% endif %}
            </ul>
        </div>
    </li>

    <!-- Post a comment -->
    <script>
        $("#{{comment.id}}").submit(function(event) {
            event.preventDefault();
            ref = $(this)
            $.ajax({
                type:'POST',
                async: true,
                cache: false,
                url:'{% url "forum:post_comment" %}',
                data: {
                    csrfmiddlewaretoken: $(this).find("input[type='hidden']").val(),
                    forum_id: "{{ forum_id }}",
                    text: $(this).find("textarea").val(),
                    comment_id: ref.attr('id')
                },
                success: function(data) {
                    ref.parents().eq(3).find(".subcomments ul").first().prepend(data)
                    ref.find("textarea").val('')
                }
            });
        })
    </script>

    <script>
        var comment_textarea = document.querySelectorAll('#comment_post_form textarea, .comment_reply_form textarea');

        comment_textarea.forEach(function(node) {
          node.setAttribute('style', 'height:' + (comment_textarea.scrollHeight) + 'px;overflow-y:hidden;');
          node.addEventListener("input", OnInput, false);
        })

        function OnInput() {
          this.style.height = 'auto';
          this.style.height = (this.scrollHeight) + 'px';
        }
    </script>
{%endfor%}

xb1/xb1/forum/templates/forum_detail.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block include %}
    <link rel="stylesheet" href="{% static 'css/forum_detail.css' %}" >
    <link rel="stylesheet" href="{% static 'css/forum_comments.css' %}" >
{% endblock %}

{% block content %}
<div class="forum_list_topnav">
{%if perms.articles.change_forum_category %}
	<a class="delete_forum_button" onclick="openDialog()">{% trans "Delete forum" %}<i class="fas fa-trash-alt"></i></a>
{%endif%}
</div>

<div class="forum_detail_content">
	<div class="forum_detail_info">
		<a class="forum_category_title" href="{% url 'forum:forum_list' pk=object.category.pk %}">{{object.category.title}} /</a>
		<a class="forum_thread_title" href="{% url 'forum:forum_detail' pk=object.pk %}">{{object.title}}</a>
	</div>

	<div class="forum_detail_info2">
		{% if object.description %}
		<div class="forum_thread_description">{{object.description}}</div>
		{% endif %}

		{% if user.is_authenticated %}
		<form id="comment_post_form" method="POST">
			{% csrf_token %}
			<textarea required rows=1 placeholder="Add a comment"></textarea>
			<button class="forum_detail_post">{% trans "Post" %}</button>
		</form>
		<script src="{% static 'js/articles_detail.js' %}"></script>
		<!-- Post a new comment and display it -->
		<script>
			document.getElementById("comment_post_form").onsubmit = function(event) {
				event.preventDefault();
				$.ajax({
					type:'POST',
					async: true,
					cache: false,
					url:'{% url "forum:post_comment" %}',
					data: {
						csrfmiddlewaretoken: $("#comment_post_form input[type='hidden']").val(),
						forum_id: "{{ forum_id }}",
						text: $("#comment_post_form textarea").val(),
						comment_id: -1,
					},
					success: function(data) {
						$('.comments ul:first').prepend(data)
						$('#comment_post_form textarea').val('')
					}
				});
			}
		</script>
		{% endif %}
	</div>

    <div class="comments">
        <ul>
            {% include "forum_comment.html" %}
        </ul>
    </div>

</div>
{% endblock %}


{% block modal %}

{%if perms.articles.change_forum_category %}
    <h1>{% trans "Delete forum" %}</h1>
    <p>{% trans "Do you really want to delete forum:" %} <strong>{{ title }}</strong>?</p>
    <p>{% trans "All related comments will be deleted!" %}</p>

    <form action="{% url 'forum:delete_forum' pk=object.pk %}" method="POST">
        {% csrf_token %}
        <button name="forum_pk" value="{{object.pk}}">{% trans "Confirm" %}</button>
    </form>
{% endif %}

{% endblock %}

xb1/xb1/forum/templates/forum_form.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block include %}
<link rel="stylesheet" href="{% static 'css/forum_form.css' %}" >
{% endblock %}

{% block content %}
<form id ="article_form" method="post" enctype="multipart/form-data">{% csrf_token %}
    <div style="width: 80%; margin: 0 auto;">
        {% for field in form.visible_fields %}
            {{ field.label_tag }}
            {{ field }}
        {% endfor %}
    </div>
    <button class="article_form_btn" type="submit">{% trans 'Submit' %}</button>
</form>
{% endblock %}

xb1/xb1/forum/templates/forum_index.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block include %}
<link rel="stylesheet" href="{% static 'css/forum_index.css' %}" >
{% endblock %}

{% block content %}

{%if perms.articles.change_forum_category %}
<div class="forum_index_topnav">
    <a href="{% url 'forum:create_forum_category' %}" class="new_forum_button">Nové téma<i class="fas fa-plus"></i></a>
</div>
{%endif%}

<div class="forum_index_content">
{% for category in categories %}
    <div class="forum_category_wrapper">

        {% if category.pk != False %}
            <a class="forum_category" href="{% url 'forum:forum_list' pk=category.pk %}">
        {% else %}
            <a class="forum_category" href="{% url 'forum:forum_list' %}">
        {% endif %}
                
            <i class="fas fa-sticky-note fa-2x"></i>
            <div class=forum_category_info>
                <div class="forum_category_title">{{ category.title }}</div>
                {%if category.description%}
                <div class="forum_category_description">{{ category.description }}</div>
                {%endif%}
            </div>
        </a>

        {% if category.latest %}
        <a class="forum_latest_thread" href="{% url 'forum:forum_detail' pk=category.latest.pk %}">
            <div class="forum_latest_thread_title">{{ category.latest.title }}</div>
            {%if category.description%}
            <div class="forum_category_description">{{category.latest.description}}</div>
            {%endif%}
        </a>
        {% endif %}
    </div>
{% endfor %}
</div>
{% endblock %}

xb1/xb1/forum/templates/forum_list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block include %}
<link rel="stylesheet" href="{% static 'css/forum_list.css' %}" >
{% endblock %}

{% block content %}

<div class="forum_list_topnav">
{% if is_open or perms.articles.add_forum and category_pk %}
    <a href="{% url 'forum:create_forum' pk=category_pk %}" class="new_thread_button">{% trans "New thread" %}<i class="fas fa-plus"></i></a>
{% endif %}

{%if perms.articles.change_forum_category and category_pk %}
    <a href="{% url 'forum:update_forum_category' pk=category_pk %}" class="edit_forum_button">{% trans "Edit category" %}<i class="fas fa-edit"></i></a>
    <a class="delete_forum_button" onclick="openDialog()">{% trans "Delete category" %}<i class="fas fa-trash-alt"></i></a>
{%endif%}
</div>

<div class="forum_list_content">

    {% if category_pk %}
        <div class="forum_category_info">
            <a class="forum_category_title" href="{% url 'forum:forum_list' pk=category_pk %}">{{title}}</a>
        </div>
    {% endif %}

    <div>
    {% for forum in forums %}
        <a class="forum_thread" href="{% url 'forum:forum_detail' pk=forum.pk %}">
            <i class="fas fa-comment-alt fa-2x"></i>
            <div class="forum_thread_name">
                <div class="forum_thread_title">{{ forum.title }}</div>
                {%if forum.description%}
                <div class="forum_thread_description">{{ forum.description }}</div>
                {%endif%}
            </div>
            <table class="forum_thread_info">
                <tr>
                    <td>{% trans "Last post" %}:</td>
                    <td>{{forum.last_date}}</td>
                </tr>
                <tr>
                    <td>{% trans "Replies" %}:</td>
                    <td>{{forum.replies_cnt}}</td>
                </tr>
            </table>


        </a>
    {% endfor %}
    </div>

</div>
{% endblock %}



{% block modal %}

{%if perms.articles.change_forum_category and category_pk %}
    <h1>{% trans "Delete category" %}</h1>
    <p>{% trans "Do you really want to delete forum category:" %} <strong>{{ title }}</strong>?</p>
    <p>{% trans "All related forums will be deleted!" %}</p>

    <form action="{% url 'forum:delete_forum_category' pk=category_pk %}" method="POST">
        {% csrf_token %}
        <button name="category_pk" value="{{category_pk}}">{% trans "Confirm" %}</button>
    </form>
{% endif %}

{% endblock %}