xb1/xb1/articles/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'articles'
urlpatterns = [

    # Articles
    url(r'^$', views.ArticleListView.as_view(), name="article_list"),
    url(r'^create/$', views.ArticleCreateView.as_view(), name="article_create"),
    url(r'^(?P<pk>\d+)/', views.ArticleUpdateView.as_view(), name="article_update"),
    url(r'^(?P<slug>[\w-]+)/$', views.ArticleDetailView.as_view(), name="detail"),
    url(r'^get_articles_by_category', views.GetArticlesByCategoryView.as_view(), name="get_articles_by_category"),
    url(r'^get_all_articles', views.GetAllArticlesView.as_view(), name="get_all_articles"),
    url(r'^search_articles', views.ArticleSearchView.as_view(), name="search_articles"),
    url(r'^article_delete', views.ArticleDeleteView.as_view(), name="article_delete"),
    url(r'^hide_article', views.HideArticleView.as_view(), name="hide_article"),
    url(r'^publish_article', views.PublishArticleView.as_view(), name="publish_article"),

    # Comments
    url(r'^post_comment', login_required(views.PostCommentView.as_view()), name="post_comment"),
    url(r'^comment/(?P<pk>\d+)/ban', views.BanCommentView.as_view(), name="ban_comment"),
    url(r'^comment/(?P<pk>\d+)/unban', views.UnbanCommentView.as_view(), name="unban_comment"),

    # Tags
    url(r'^create_tag', views.TagCreateView.as_view(), name="create_tag"),

    # Categories
    url(r'^create_category', views.CategoryCreateView.as_view(), name="create_category"),
    url(r'^delete_category', views.CategoryDeleteView.as_view(), name="delete_category"),


]

xb1/xb1/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import activate_registration, PasswordChangeView, EmailChangeView, activate_email, CKEditorBrowseView, CKEditorUploadView, CKEditorDeleteView
from django.contrib.auth import views as auth_views

admin.autodiscover()

urlpatterns = [
    # Index
    url(r'^$', views.IndexView.as_view(), name='index'),

    # Admin urls
    url(r'^users/$', views.UserListView.as_view(), name='user_list'),
    url(r'^users/user_detail/(?P<pk>\d+)/$', views.UserDetailView.as_view(), name='user_detail'),
    url(r'^users/user_detail/(?P<pk>\d+)/comments/$', views.UserCommentsView.as_view(), name='user_comments'),

    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^admin_tools/ ', include('admin_tools.urls')),

    # Login redirect urls
    url(r'^D7E88079F0C53EE2AC930A3D7300218AC6F0615FECD4A91CFDBA/$', views.LoginViewModal.as_view(), name='login_modal'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),

    # Password reset urls
    url(r'^password_reset/$', views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^password_reset_complete/$', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # Profile view
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),

    # Register
    url(r'^register/', views.Register.as_view(), name='register'),

    # Apps.
    url(r"^articles/", include("xb1.articles.urls")),
    url(r"^core/", include("xb1.core.urls")),
    url(r"^contact/", include("xb1.contact.urls")),
    url(r"^forum/", include("xb1.forum.urls")),
    url(r"^eshop/", include("xb1.eshop.urls")),
    url(r"^shop/", include("xb1.shop.urls")),

    url(r"^sent/", views.ActivationSentView.as_view(), name="activation_sent"),
    path('activate_registration/<slug:uidb64>/<slug:token>/', activate_registration, name='activate_registration'),

    url(r'^profile/change_password/', PasswordChangeView.as_view(), name='change_password'),
    url(r'^profile/change_email/', EmailChangeView.as_view(), name='change_email'),
    path('activate_email/<slug:uidb64>/<slug:token>/', activate_email, name='activate_email'),

    # CKEDITOR
    # url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^ckeditor/upload/', CKEditorUploadView.as_view(), name='ckeditor_upload'),
    url(r'^ckeditor/browse/', CKEditorBrowseView.as_view(), name='ckeditor_browse'),
    url(r'^ckeditor/delete/', CKEditorDeleteView.as_view(), name='ckeditor_delete'),

    path('captcha/', include('captcha.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

xb1/xb1/articles/models.py
from django.db import models
from model_utils.models import TimeStampedModel
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from os.path import basename, splitext
from django.utils.text import slugify


from ..core.models import User, DeleteMixin

import random

class Category(DeleteMixin):
    """
    Category model for filtering articles.
    """

    name = models.CharField(_("Name"), max_length=100)

    def __str__(self):
        return self.name


class Tag(DeleteMixin):
    """
    Category tags model for filtering articles.
    """

    name = models.CharField(_("Name"), max_length=100)

    def __str__(self):
        return self.name


class UploadedFile(models.Model):
    """
    CKEditor model for storing uploaded files.
    """

    uploaded_file = models.FileField(upload_to=u"article_content_images/")
    uploaded_at = models.DateField(editable=False, auto_now_add=True)

    def __str__(self):
        return basename(self.uploaded_file.path)

    def url(self):
        return self.uploaded_file.url

    def delete(self, *args, **kwargs):
        file_storage, file_path = self.uploaded_file.storage, self.uploaded_file.path
        super(UploadedFile, self).delete(*args, **kwargs)
        name, ext = splitext(file_path)
        file_storage.delete(file_path)
        file_storage.delete(name + "_thumb" + ext)

class Article(TimeStampedModel, DeleteMixin):

    HIDDEN = 0
    PUBLISHED = 1
    STATE_CHOICES = (
        (HIDDEN, _("Hidden")),
        (PUBLISHED, _("Published"))
    )

    title          = models.CharField(verbose_name=_("Title"), max_length=100)
    thumbnail      = models.ImageField(verbose_name=_("Thumbnail"), null=True, blank=True, upload_to='thumbnails')
    preview_text   = models.TextField(verbose_name=_("Preview text"), blank=True, null=False, default=_("Read more..."))
    author         = models.ForeignKey(User, verbose_name=_("Author"), on_delete=models.SET_NULL, blank=True, null=True)
    slug           = models.SlugField(verbose_name=_("Slug"), unique=True, max_length=100, blank=True, null=True)
    category       = models.ManyToManyField(Category, verbose_name=_("Category"), blank=True)
    tags           = models.ManyToManyField(Tag, verbose_name=_("Tag"), blank=True)
    allow_comments = models.BooleanField(verbose_name=_("Comments allowed"), default=True)
    published_from = models.DateTimeField(verbose_name=_("Published from"), default=timezone.now, null=True, blank=True)
    published_to   = models.DateTimeField(verbose_name=_("Published to"), null=True, blank=True)
    text           = RichTextField(verbose_name=_("Text"), blank=True, null=True)
    sources        = models.TextField(verbose_name=_("Sources"), blank=True, null=True)
    article_state  = models.PositiveSmallIntegerField(verbose_name=_("State"), choices=STATE_CHOICES, default=HIDDEN)

    def save(self, *args, **kwargs):
        if self.slug is None:
            self._generate_slug()

        super().save(*args, **kwargs)

    def _generate_slug(self):

        slg = slugify(self.title)

        # Test if slug exists
        while Article.objects.filter(slug=slg).exists():
            slg = slg + "_" + str(random.randint(0, 1000))

        self.slug = slg


class ForumCategory(DeleteMixin):

    title = models.CharField(verbose_name=_("Title"), max_length=100)
    is_open = models.BooleanField(verbose_name=_("Is public"), default=True)
    description = models.TextField(verbose_name=_("Category description"), blank=True, null=True)

    def __str__(self):
        return self.title


class Forum(TimeStampedModel, DeleteMixin):

    title = models.CharField(verbose_name=_("Title"), max_length=100)
    description = models.TextField(verbose_name=_("Forum description"), blank=True, null=True)
    author = models.ForeignKey(User, verbose_name=_("Author"), on_delete=models.SET_NULL, blank=True, null=True)
    is_closed = models.BooleanField(verbose_name=_("Is closed"), default=False)
    category = models.ForeignKey(ForumCategory, verbose_name=_("Category"), on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title


class Comment(TimeStampedModel, DeleteMixin):

    article = models.ForeignKey(Article, verbose_name=_("Article"), on_delete=models.CASCADE, blank=True, null=True)
    forum = models.ForeignKey(Forum, verbose_name=_("Forum"), on_delete=models.CASCADE, blank=True, null=True)
    reaction_to = models.ForeignKey("Comment", verbose_name=_("Reacts to"), on_delete=models.CASCADE, blank=True, null=True)
    author = models.ForeignKey(User, verbose_name=_("Author"), on_delete=models.SET_NULL, blank=True, null=True)
    text = RichTextField(verbose_name=_("Text"), blank=True, null=True, config_name="comment")
    is_censured = models.BooleanField(verbose_name=_("Is censured"), default=False)
    date = models.DateTimeField(verbose_name=_("Posted on"), default=timezone.now, null=False, blank=False, editable=False)

    def __str__(self):
        return self.text if self.text else "---"

xb1/xb1/articles/forms.py
from django import forms

import django.utils.formats

from .models import Article, Comment, Category, Tag
from ..core.widgets import DatePickerInput
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django.forms.widgets import CheckboxSelectMultiple

class ArticleForm(forms.ModelForm):

    class Meta:
        forms.DateTimeField
        model = Article
        fields = [
            "title", "thumbnail","preview_text" , "text", "slug", "category",
            "tags", "allow_comments", "sources", "article_state", "published_from",
            "published_to"
        ]

    def __init__(self, *args, **kwargs):

        super(ArticleForm, self).__init__(*args, **kwargs)

        self.fields["published_from"].widget = DatePickerInput()
        self.fields["published_from"].widget.attrs["autocomplete"] = "off"

        self.fields["published_to"].widget = DatePickerInput()
        self.fields["published_to"].widget.attrs["autocomplete"] = "off"

        self.fields["text"].widget = CKEditorUploadingWidget()

        self.fields["category"].widget = CheckboxSelectMultiple()
        self.fields["category"].queryset = Category.objects.all()

    def clean(self):

        cleaned_data = super(ArticleForm, self ).clean()

        return cleaned_data

xb1/xb1/articles/templates/article_comment.html
{% load i18n %}
{% for comment in comments %}
    <li>
    <div class="comment">
        <img class=comment_profile_pic src="{{comment.author.profile.image.url}}">
        <div class="comment_content">
            <div class= "comment_header">
                <div class="comment_nickname">{{comment.author.profile.nickname}}</div>
                <div class="comment_date">{{comment.date}}</div>
            </div>

            {% if comment.is_censured %}
                <div class="comment_text">
                    <b>{% trans "Comment has been banned for inappropriate speech." %}</b>
                </div>
            {% else %}
                <div class="comment_text">{{ comment.text }}</div>
            {% endif %}

            {% if user.is_authenticated %}
                <!-- Admin section for banning -->
                {% if perms.articles.change_comment %}
                    {% if not comment.is_censured %}
                        <a href="{% url 'articles:ban_comment' pk=comment.id %}">
                            <button>
                                {% trans "Censure" %}<i class="fas fa-ban" style="font-size: 15px;"></i>
                            </button>
                        </a>
                    {% else %}
                        <a href="{% url 'articles:unban_comment' pk=comment.id %}">
                            <button>
                                {% trans "Un-censure" %}<i class="fas fa-lock-open" style="font-size: 15px;"></i>
                            </button>
                        </a>
                        <div class="comment_text">
                            {% trans "Banned text:" %}{{comment.text }}
                        </div>
                    {% endif %}
                {% endif %}

                <button class="comment_section_reply_button" id="button_comment_{{comment.id}}" onclick="showReply('comment_{{comment.id}}')">{% trans "Reply" %}</button>

                <div id="comment_{{comment.id}}" style="display: none" >
                    <form id="{{comment.id}}" class="comment_reply_form" method="POST">
                        {% csrf_token %}
                        <!-- {{ comment.form.text }} -->
                        <textarea required rows=1 placeholder="Add a reply"></textarea>
                        <button class="comment_section_button">{% trans "Reply" %}</button>
                    </form>
                </div>

                <script>
                    function showReply(comment_id) {
                        var x = document.getElementById(comment_id);
                        x.style.display = "block";

                        var y = document.getElementById("button_" + comment_id);
                        y.style.display = "none";
                    }
                </script>
            {% endif %}
        </div>
    </div>

        <div class="subcomments">
            <ul>
                {% if comment.comments|length %}
                    {% include "article_comment.html" with comments=comment.comments %}
                {% endif %}
            </ul>
        </div>
    </li>

    <!-- Post a comment -->
    <script>
        $("#{{comment.id}}").submit(function(event) {
            event.preventDefault();
            ref = $(this)
            $.ajax({
                type:'POST',
                async: true,
                cache: false,
                url:'{% url "articles:post_comment" %}',
                data: {
                    csrfmiddlewaretoken: $(this).find("input[type='hidden']").val(),
                    article_id: "{{ article.pk }}",
                    text: $(this).find("textarea").val(),
                    comment_id: ref.attr('id')
                },
                success: function(data) {
                    ref.parents().eq(3).find(".subcomments ul").first().prepend(data)
                    ref.find("textarea").val('')
                }
            });
        })
    </script>
{%endfor%}

xb1/xb1/articles/templates/article_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{%block include%}
<link rel="stylesheet" href="{% static 'css/article_detail.css' %}" >
<link rel="stylesheet" href="{% static 'css/article_comments.css' %}" >
{%endblock%}

{%block content%}
	<div class="article_wrapper">
		<div class="article">
			<h2>{{ article.title }}</h2>
			<hr>
			<div class="article_date">
				<p>{{ article.modified }}</p>
			</div>
			<div class="article_text">
				<p>{{ article.text | safe }}</p>
			</div>
			<div class="article_footer">
				<div class="article_footer_left">
					{% if categories %}
					<div class="article_footer_item">
						<h1>{% trans "categories" %}</h1>
						{% for category in categories %}
						<p class="article_category">{{ category }}</p>
						{% endfor %}
					</div>
					{% endif %}
					<div class="article_footer_item">
						<h1>{% trans "author" %}</h1>
						<p>{{ article.author.profile.nickname }}</p>
					</div>
				</div>
				<div class="article_footer_right">
					{% if tags %}
					<div class="article_footer_item">
						<h1 class="tags_h">{% trans "tags" %}</h1>
						{% for tag in tags %}
						<div class="article_tag">{{ tag }}</div>
						{% endfor %}
					</div>
					{% endif %}
					{% if article.sources %}
					<div class="article_footer_item">
						<h1>{% trans "sources" %}</h1>
						<p>{{ article.sources }}</p>
					</div>
					{% endif %}
				</div>
				{%if perms.articles.change_article %}
				<br>
				<a href="/articles/{{ article.id }}"><button class="edit_button">{% trans "Edit Article" %}</button></a>
				{% endif %}
			</div>
		</div>
	</div>

	{% if article.allow_comments %}

		<div class="comment_wrapper">
			<ul>
				{% include "article_comment.html" %}
			</ul>

			{% if user.is_authenticated %}
				<form id="comment_post_form" method="POST">
					{% csrf_token %}
					<!-- {{ comment_form.text }} -->
					<textarea required rows=1 placeholder="Add a comment"></textarea>
					<button class="comment_section_button">{% trans "Post" %}</button>
				</form>

				<script src="{% static 'js/articles_detail.js' %}"></script>
				<!-- Post a new comment and display it -->
				<script>
					document.getElementById("comment_post_form").onsubmit = function(event) {
						event.preventDefault();
						$.ajax({
							type:'POST',
							async: true,
							cache: false,
							url:'{% url "articles:post_comment" %}',
							data: {
								csrfmiddlewaretoken: $("#comment_post_form input[type='hidden']").val(),
								article_id: "{{ article.pk }}",
								text: $("#comment_post_form textarea").val(),
								comment_id: -1,
							},
							success: function(data) {
								$('#comment_post_form').before(data)
								$('#comment_post_form textarea').val('')
							}
						});
					}
				</script>
			{% endif %}
		</div>

	{% endif %}
{% endblock %}

xb1/xb1/articles/templates/articles.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block include %}
<link rel="stylesheet" href="{% static 'css/articles.css' %}" >
{% endblock %}

{% block content %}
<div class="articles_content">
    <div class="articles_topnav">

        {%if perms.articles.add_article %}
        <a href="{% url 'articles:article_create' %}" class="new_article_button">{%trans "Create article"%}<i class="fas fa-plus"></i></a>
        
        <form class="new_category_form" method="POST" action="{% url 'articles:create_category' %}">
            <button class="new_category_button" type="button">{%trans "Add category"%}<i class="fas fa-list"></i></button>
            <div class="new_category_input">
                {% csrf_token %}
                <input type="text" name="category_name" placeholder="{%trans "Category"%}">
                <button type="submit"><i class="fas fa-plus"></i></button>
            </div>
        </form>
        {%endif%}

        <form class="article_search">
            <input type="text" required placeholder="{%trans "Search articles"%}">
            <button type="submit"><i class="fa fa-search"></i></button>
        </form>
    </div>
    <div class="articles_categories">
        <button class="slider_button slider_back">
            <i class="fas fa-angle-left fa-3x"></i>
        </button>

        <div class="articles_categories_slider_menu">
            <div class=articles_categories_wrapper>
                <div>
                    <button class="article_category_all article_category_active">{%trans "All"%}</button>
                </div>

                {% for category in categories %}
                <div class="article_category_option">
                    <button class="article_category" id="{{category.id}}">{{category}}</button>
                    {%if perms.articles.change_article %}
                    <form action="{% url 'articles:delete_category' %}" method="POST">
                        {% csrf_token %}
                        <button class="article_category_delete_button" name="category_id" value="{{category.id}}"><i class="fas fa-times-circle"></i></button>
                    </form>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
        </div>

        <button class="slider_button slider_next">
            <i class="fas fa-angle-right fa-3x"></i>
        </button>
    </div>

    <div class="articles_list">
        {% include "get_articles.html" with articles=object_list %}
    </div>
</div>

{%if perms.articles.change_article %}
<script>
    $(".article_category_delete_button").click(function(e) {
        icon = $(this).find(".fas")

        if(icon.hasClass("fa-times-circle")) {
            e.preventDefault()
            icon.fadeOut(300, function() {
                $(this).removeClass("fa-times-circle")
            })
            icon.fadeIn(300, function() {
                $(this).addClass("fa-trash-alt")
            })
            $(this).focus()
        }
    })

    $(".article_category_delete_button").focusout(function() {
        icon = $(this).find(".fas")

        if(icon.hasClass("fa-trash-alt")) {
            icon.fadeOut(300, function() {
                $(this).removeClass("fa-trash-alt")
            })

            icon.fadeIn(300, function() {
                $(this).addClass("fa-times-circle")
            })
        }
    })
</script>
{%endif%}

<script>
    $(".article_search").submit(function(event) {
        event.preventDefault()
        ref = $(this)
        $('*').removeClass('article_category_active')
        $.ajax({
            type:'GET',
            async: true,
            cache: false,
            url:'{% url "articles:search_articles" %}',
            data: {
                csrfmiddlewaretoken: "{{ csrf_token }}",
                keywords: ref.find('input[type=text]').val()
              },
              success: function(data) {
                  $('.articles_list').html(data)
              }
        });
    })
</script>

<script>
    $(".article_category_all").click(function() {
        ref = $(this)
        $.ajax({
            type:'GET',
            async: true,
            cache: false,
            url:'{% url "articles:get_all_articles" %}',
            data: {
                csrfmiddlewaretoken: "{{ csrf_token }}"
              },
              success: function(data) {
                  $('.articles_list').html(data)
              }
          });
    })
</script>

<script>
    $(".article_category").click(function() {
        ref = $(this)
        $.ajax({
            type:'GET',
            async: true,
            cache: false,
            url:'{% url "articles:get_articles_by_category" %}',
            data: {
                csrfmiddlewaretoken: "{{ csrf_token }}",
                category: ref.attr('id')
              },
              success: function(data) {
                  $('.articles_list').html(data)
              }
          });
    })
</script>

<script src="{% static 'js/articles.js' %}"></script>
{% endblock %}

xb1/xb1/articles/templates/articles_form.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{%block include%}
<link rel="stylesheet" href="{% static 'css/article_form.css' %}" />
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
{% endblock %}

{%block content%}
<form id ="article_form" method="post" enctype="multipart/form-data">{% csrf_token %}
  <table>
    {% for field in form.visible_fields %}
      <tr>
        <th>{{ field.label_tag }}</th>
        <td>
          {{ field.errors }}
          {{ field }}
          {{ field.help_text }}
        </td>
      </tr>
    {% endfor %}
  </table>
  <input type="submit" value="{% trans 'Submit' %}">
</form>

<script>
  $('#id_tags').select2({
	  tags: true,
    tokenSeparators: [','], 
    placeholder: "Add your tags here",
    selectOnclose: true,
    createTag: function(params) {
      return {
          id: params.term,
          text: params.term,
          newTag: true,
      }
              },
  }).on("select2:select", function(e) {
    data = e.params.data
    if(data.newTag == true) {
      ref = $("#id_tags option[value=" + data.id + "]")
      $.ajax({
        type:'POST',
        cache: false,
        url:'{% url "articles:create_tag" %}',
        dataType: "json",
        data: {
            csrfmiddlewaretoken: "{{ csrf_token }}",
            tag_text: data.text
          },

        success: function(ret) {
          ref.remove()
          var newOption = new Option(data.text, ret.tag_id, true, true);
          $("#id_tags").append(newOption).trigger('change');
        }
      });
    }
  });
</script>

<a class = "back" href="{% url 'articles:article_list' %}">{% trans "Back" %}</a> <br>
    </div>
{% endblock %}

xb1/xb1/articles/templates/get_articles.html
{% load i18n %}
{% for article in articles %}

    {% if article.article_state == 1 or perms.articles.change_article %}


        {% if article.article_state == 1 %}
            <div class="article_preview">
        {% else %}
            <div class="article_preview article_hidden">
        {%endif%}

                {%if article.thumbnail %}
                    <img class="preview_thumbnail" src="{{article.thumbnail.url}}">
                {%endif%}
                <a href="{% url 'articles:detail' slug=article.slug %}" class="preview_content">
                    <div class="preview_title">{{article.title}}</div>
                    <div class="preview_info">
                        {%if article.author.profile.image%}
                        <img class="preview_author_profile_image" src="{{article.author.profile.image.url}}">
                        {%endif%}
                        <div class="preview_author_nickname">{{article.author.profile.nickname}}</div>
                        <div class="preview_modified">{{article.modified}}</div>
                    </div>
                    <div class="preview_text">{{ article.preview_text | safe | default_if_none:"" }}</div>
                </a>
                <div class="article_preview_tags">
                    {%for tag in article.article_tags%}
                        <div class="article_tag">{{tag}}</div>
                    {%endfor%}
                </div>
                {%if perms.articles.change_article%}
                    <div class="preview_utilities">

                        {% if article.article_state == 1 %}
                        <button class="preview_hide_button" id="{{ article.id }}">{%trans "Hide"%}</button>
                        {% else %}
                        <button class="preview_publish_button" id="{{ article.id }}">{%trans "Publish"%}</button>
                        {%endif%}


                        <a class="preview_edit_button" href="{% url 'articles:article_update' pk=article.pk %}">{%trans "Edit"%}</a>
                        <button class="preview_delete_button" id="{{ article.id }}">{%trans "Delete"%}</button>
                    </div>
                {%endif%}
            </div>
    {%endif%}
{% endfor %}

{%if perms.articles.change_article%}
<script>
    function hide_function(event) {
        event.preventDefault();
        ref = $(this)
        $.ajax({
                type:'POST',
                async: true,
                cache: false,
                url:'{% url "articles:hide_article" %}',
                data: {
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    article_id: ref.attr('id')
                },
                success: function(data) {
                    ref.attr('class', "preview_publish_button");
                    ref.text('{%trans "Publish" %}');
                    ref.parents().eq(1).addClass("article_hidden");
                    ref.one('click', publish_function);
                }
            });
    };

    function publish_function(event) {
        event.preventDefault();
        ref = $(this)
        $.ajax({
                type:'POST',
                async: true,
                cache: false,
                url:'{% url "articles:publish_article" %}',
                data: {
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    article_id: ref.attr('id')
                },
                success: function(data) {
                    ref.attr('class', "preview_hide_button");
                    ref.text('{%trans "Hide"%}');
                    ref.parents().eq(1).removeClass("article_hidden");
                    ref.one('click', hide_function);
                }
            });
    };

    $(".preview_hide_button").one('click' ,hide_function);
    $(".preview_publish_button").one('click', publish_function);
</script>


<script>
    $(".preview_delete_button").click(function(event) {
        event.preventDefault()
        if ($(this).hasClass("delete_confirmation")) {
            ref = $(this)
            $.ajax({
                type:'POST',
                async: true,
                cache: false,
                url:'{% url "articles:article_delete" %}',
                data: {
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    article_id: ref.attr('id')
                },
                success: function(data) {
                    ref.parents().eq(1).remove()
                }
            });
        }else {
            $(this).text('{%trans "Confirm"%}')
            $(this).addClass("delete_confirmation")
        }
    })

    $(".preview_delete_button").focusout(function(event) {
        $(this).text('{%trans "Delete"%}')
        $(this).removeClass("delete_confirmation")
    })
</script>
{%endif%}