xb1/xb1/articles/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'articles'
urlpatterns = [

    # Articles
    url(r'^$', views.ArticleListView.as_view(), name="article_list"),
    url(r'^create/$', views.ArticleCreateView.as_view(), name="article_create"),
    url(r'^(?P<pk>\d+)/', views.ArticleUpdateView.as_view(), name="article_update"),
    url(r'^(?P<slug>[\w-]+)/$', views.ArticleDetailView.as_view(), name="detail"),
    url(r'^get_articles_by_category', views.GetArticlesByCategoryView.as_view(), name="get_articles_by_category"),
    url(r'^get_all_articles', views.GetAllArticlesView.as_view(), name="get_all_articles"),
    url(r'^search_articles', views.ArticleSearchView.as_view(), name="search_articles"),
    url(r'^article_delete', views.ArticleDeleteView.as_view(), name="article_delete"),
    url(r'^hide_article', views.HideArticleView.as_view(), name="hide_article"),
    url(r'^publish_article', views.PublishArticleView.as_view(), name="publish_article"),

    # Comments
    url(r'^post_comment', login_required(views.PostCommentView.as_view()), name="post_comment"),
    url(r'^comment/(?P<pk>\d+)/ban', views.BanCommentView.as_view(), name="ban_comment"),
    url(r'^comment/(?P<pk>\d+)/unban', views.UnbanCommentView.as_view(), name="unban_comment"),

    # Tags
    url(r'^create_tag', views.TagCreateView.as_view(), name="create_tag"),

    # Categories
    url(r'^create_category', views.CategoryCreateView.as_view(), name="create_category"),
    url(r'^delete_category', views.CategoryDeleteView.as_view(), name="delete_category"),


]

xb1/xb1/contact/urls.py
from django.conf.urls import url

from . import views

app_name = 'contact'
urlpatterns = [

    url(r'^$', views.ContactFormView.as_view(), name="contact"),

]

xb1/xb1/core/urls.py
from django.conf.urls import url

from . import views

app_name = 'core'
urlpatterns = [
    url(r'^switch-language/$', views.SwitchLanguageRedirectView.as_view(), name='switch_language'),
]

xb1/xb1/eshop/urls.py
from django.conf.urls import url

from . import views

app_name = 'eshop'
urlpatterns = []

xb1/xb1/forum/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'forum'
urlpatterns = [

    # Forum
    url(r'^$', views.ForumIndexView.as_view(), name="index"),
    url(r'^category/(?P<pk>\d+)/$', views.ForumListView.as_view(), name="forum_list"),
    url(r'^category/$', views.ForumListView.as_view(), name="forum_list"),
    url(r'^forum-category-create/$', views.ForumCategoryCreateView.as_view(), name="create_forum_category"),
    url(r'^forum-category-update/(?P<pk>\d+)/$', views.ForumCategoryUpdateView.as_view(), name="update_forum_category"),
    url(r'^forum-category-delete/(?P<pk>\d+)/$', views.ForumCategoryDeleteView.as_view(), name="delete_forum_category"),
    url(r'^forum-detail/(?P<pk>\d+)/$', views.ForumDetailView.as_view(), name="forum_detail"),
    url(r'^forum-category/(?P<pk>\d+)/create-forum/$', views.ForumCreateView.as_view(), name="create_forum"),
    url(r'^forum-delete/(?P<pk>\d+)/$', views.ForumDeleteView.as_view(), name="delete_forum"),

    url(r'^post-comment', login_required(views.PostCommentView.as_view()), name="post_comment"),
]

xb1/xb1/shop/urls.py
from django.conf.urls import url

from . import views

app_name = 'shop'
urlpatterns = [
    url(r'^$', views.ShopIndex.as_view(), name='shopView'),

    # By PK of Item
    url(r'^cart/insert/(?P<pk>[0-9]+)$', views.CartInsertItemView.as_view(), name="cartinsert"),

    # By PK of CartEntry 
    url(r'^cart/update/(?P<pk>[0-9]+)/add$', views.CartAddItemView.as_view(), name="cartadd"),
    url(r'^cart/update/(?P<pk>[0-9]+)/remove$', views.CartRemoveItemView.as_view(), name="cartremove"),
    url(r'^cart/update/(?P<pk>[0-9]+)/discard$', views.CartDiscardItemView.as_view(), name="cartdiscard"),
    url(r'^cart/update/discard', views.CartDiscardItemView.as_view(), name="cartdiscardall"),
    url(r'^cart/update/(?P<pk>[0-9]+)/set/(?P<spec>[0-9]+)', views.CartSetSpecificationView.as_view(), name="cartspecificationset"),

    url(r'^admin/item/list$', views.ItemListView.as_view(), name="adminItemList"),
    url(r'^admin/item/create$', views.ItemCreateView.as_view(), name="adminItemCreate"),
    url(r'^admin/item/create/(?P<pk>[0-9]+)$', views.ItemCreateAsView.as_view(), name="adminItemCreateAs"),
    url(r'^admin/item/delete/(?P<pk>[0-9]+)$', views.ItemDeleteView.as_view(), name="adminItemDelete"),
    url(r'^admin/item/detail/(?P<pk>[0-9]+)$', views.ItemDetailView.as_view(), name="adminItemDetail"),
    url(r'^admin/item/update/(?P<pk>[0-9]+)$', views.ItemUpdateView.as_view(), name="adminItemUpdate"),
    url(r'^admin/item/deactivate/(?P<pk>[0-9]+)$', views.ItemDeactivateView.as_view(), name="adminItemDeactivate"),


    url(r'^order/create$', views.OrderCreateView.as_view(), name="orderCreate"),
    url(r'^order/tracker/(?P<slug>[\w-]+)/$', views.OrderTrackerView.as_view(), name="orderTracker"),

    url(r'^user/order/list$', views.OrderListUserView.as_view(), name="userOrderList"),

    url(r'^admin/order/list$', views.OrderListView.as_view(), name="adminOrderList"),
    url(r'^admin/order/payment/confirm/(?P<pk>[0-9]+)$', views.OrderPaymentConfirmView.as_view(), name="adminOrderPaymentConfirm"),
    url(r'^admin/order/payment/revoke/(?P<pk>[0-9]+)$', views.OrderPaymentRevokeView.as_view(), name="adminOrderPaymentRevoke"),
    url(r'^admin/order/detail/(?P<pk>[0-9]+)$', views.OrderDetailView.as_view(), name="adminOrderDetail"),
]

xb1/xb1/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import activate_registration, PasswordChangeView, EmailChangeView, activate_email, CKEditorBrowseView, CKEditorUploadView, CKEditorDeleteView
from django.contrib.auth import views as auth_views

admin.autodiscover()

urlpatterns = [
    # Index
    url(r'^$', views.IndexView.as_view(), name='index'),

    # Admin urls
    url(r'^users/$', views.UserListView.as_view(), name='user_list'),
    url(r'^users/user_detail/(?P<pk>\d+)/$', views.UserDetailView.as_view(), name='user_detail'),
    url(r'^users/user_detail/(?P<pk>\d+)/comments/$', views.UserCommentsView.as_view(), name='user_comments'),

    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^admin_tools/ ', include('admin_tools.urls')),

    # Login redirect urls
    url(r'^D7E88079F0C53EE2AC930A3D7300218AC6F0615FECD4A91CFDBA/$', views.LoginViewModal.as_view(), name='login_modal'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),

    # Password reset urls
    url(r'^password_reset/$', views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^password_reset_complete/$', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # Profile view
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),

    # Register
    url(r'^register/', views.Register.as_view(), name='register'),

    # Apps.
    url(r"^articles/", include("xb1.articles.urls")),
    url(r"^core/", include("xb1.core.urls")),
    url(r"^contact/", include("xb1.contact.urls")),
    url(r"^forum/", include("xb1.forum.urls")),
    url(r"^eshop/", include("xb1.eshop.urls")),
    url(r"^shop/", include("xb1.shop.urls")),

    url(r"^sent/", views.ActivationSentView.as_view(), name="activation_sent"),
    path('activate_registration/<slug:uidb64>/<slug:token>/', activate_registration, name='activate_registration'),

    url(r'^profile/change_password/', PasswordChangeView.as_view(), name='change_password'),
    url(r'^profile/change_email/', EmailChangeView.as_view(), name='change_email'),
    path('activate_email/<slug:uidb64>/<slug:token>/', activate_email, name='activate_email'),

    # CKEDITOR
    # url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^ckeditor/upload/', CKEditorUploadView.as_view(), name='ckeditor_upload'),
    url(r'^ckeditor/browse/', CKEditorBrowseView.as_view(), name='ckeditor_browse'),
    url(r'^ckeditor/delete/', CKEditorDeleteView.as_view(), name='ckeditor_delete'),

    path('captcha/', include('captcha.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

xb1/xb1/articles/models.py
from django.db import models
from model_utils.models import TimeStampedModel
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from os.path import basename, splitext
from django.utils.text import slugify


from ..core.models import User, DeleteMixin

import random

class Category(DeleteMixin):
    """
    Category model for filtering articles.
    """

    name = models.CharField(_("Name"), max_length=100)

    def __str__(self):
        return self.name


class Tag(DeleteMixin):
    """
    Category tags model for filtering articles.
    """

    name = models.CharField(_("Name"), max_length=100)

    def __str__(self):
        return self.name


class UploadedFile(models.Model):
    """
    CKEditor model for storing uploaded files.
    """

    uploaded_file = models.FileField(upload_to=u"article_content_images/")
    uploaded_at = models.DateField(editable=False, auto_now_add=True)

    def __str__(self):
        return basename(self.uploaded_file.path)

    def url(self):
        return self.uploaded_file.url

    def delete(self, *args, **kwargs):
        file_storage, file_path = self.uploaded_file.storage, self.uploaded_file.path
        super(UploadedFile, self).delete(*args, **kwargs)
        name, ext = splitext(file_path)
        file_storage.delete(file_path)
        file_storage.delete(name + "_thumb" + ext)

class Article(TimeStampedModel, DeleteMixin):

    HIDDEN = 0
    PUBLISHED = 1
    STATE_CHOICES = (
        (HIDDEN, _("Hidden")),
        (PUBLISHED, _("Published"))
    )

    title          = models.CharField(verbose_name=_("Title"), max_length=100)
    thumbnail      = models.ImageField(verbose_name=_("Thumbnail"), null=True, blank=True, upload_to='thumbnails')
    preview_text   = models.TextField(verbose_name=_("Preview text"), blank=True, null=False, default=_("Read more..."))
    author         = models.ForeignKey(User, verbose_name=_("Author"), on_delete=models.SET_NULL, blank=True, null=True)
    slug           = models.SlugField(verbose_name=_("Slug"), unique=True, max_length=100, blank=True, null=True)
    category       = models.ManyToManyField(Category, verbose_name=_("Category"), blank=True)
    tags           = models.ManyToManyField(Tag, verbose_name=_("Tag"), blank=True)
    allow_comments = models.BooleanField(verbose_name=_("Comments allowed"), default=True)
    published_from = models.DateTimeField(verbose_name=_("Published from"), default=timezone.now, null=True, blank=True)
    published_to   = models.DateTimeField(verbose_name=_("Published to"), null=True, blank=True)
    text           = RichTextField(verbose_name=_("Text"), blank=True, null=True)
    sources        = models.TextField(verbose_name=_("Sources"), blank=True, null=True)
    article_state  = models.PositiveSmallIntegerField(verbose_name=_("State"), choices=STATE_CHOICES, default=HIDDEN)

    def save(self, *args, **kwargs):
        if self.slug is None:
            self._generate_slug()

        super().save(*args, **kwargs)

    def _generate_slug(self):

        slg = slugify(self.title)

        # Test if slug exists
        while Article.objects.filter(slug=slg).exists():
            slg = slg + "_" + str(random.randint(0, 1000))

        self.slug = slg


class ForumCategory(DeleteMixin):

    title = models.CharField(verbose_name=_("Title"), max_length=100)
    is_open = models.BooleanField(verbose_name=_("Is public"), default=True)
    description = models.TextField(verbose_name=_("Category description"), blank=True, null=True)

    def __str__(self):
        return self.title


class Forum(TimeStampedModel, DeleteMixin):

    title = models.CharField(verbose_name=_("Title"), max_length=100)
    description = models.TextField(verbose_name=_("Forum description"), blank=True, null=True)
    author = models.ForeignKey(User, verbose_name=_("Author"), on_delete=models.SET_NULL, blank=True, null=True)
    is_closed = models.BooleanField(verbose_name=_("Is closed"), default=False)
    category = models.ForeignKey(ForumCategory, verbose_name=_("Category"), on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title


class Comment(TimeStampedModel, DeleteMixin):

    article = models.ForeignKey(Article, verbose_name=_("Article"), on_delete=models.CASCADE, blank=True, null=True)
    forum = models.ForeignKey(Forum, verbose_name=_("Forum"), on_delete=models.CASCADE, blank=True, null=True)
    reaction_to = models.ForeignKey("Comment", verbose_name=_("Reacts to"), on_delete=models.CASCADE, blank=True, null=True)
    author = models.ForeignKey(User, verbose_name=_("Author"), on_delete=models.SET_NULL, blank=True, null=True)
    text = RichTextField(verbose_name=_("Text"), blank=True, null=True, config_name="comment")
    is_censured = models.BooleanField(verbose_name=_("Is censured"), default=False)
    date = models.DateTimeField(verbose_name=_("Posted on"), default=timezone.now, null=False, blank=False, editable=False)

    def __str__(self):
        return self.text if self.text else "---"

xb1/xb1/contact/forms.py
from captcha.fields import CaptchaField
from django import forms
from django.utils.translation import ugettext_lazy as _


class ContactForm(forms.Form):
    message = forms.CharField(label=_("Message"), max_length=2000, required=True, widget=forms.Textarea(
        attrs={"placeholder": _("Your message..."), "class": "form-control", "rows": 11}))
    subject = forms.CharField(label=_("Subject"), max_length=100, required=True, widget=forms.TextInput(
        attrs={"placeholder": _("Subject...")}))
    #   name = forms.CharField(label="Name", max_length=100, required=True, widget=forms.TextInput(
    #     attrs={"placeholder":"Jméno..."}))
    captcha = CaptchaField()

xb1/xb1/contact/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.db import transaction
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from .forms import ContactForm
from ..core.views import LoginMixinView
from ..settings import EMAIL_HOST_USER, FEEDBACK_EMAIL

# Create your views here.


class ContactFormView(LoginMixinView, FormView):
    """
    Contact form for authenticated users,
    sends message to email specified in settings.py
    """
    template_name = "contact.html"
    form_class = ContactForm
    success_url = reverse_lazy("index")

    def form_valid(self, form):
        try:
            with transaction.atomic():

                message = form.cleaned_data["message"] + "\n\nFrom: " + self.request.user.username
                subject = form.cleaned_data["subject"]
                send_mail(subject, message, EMAIL_HOST_USER, [FEEDBACK_EMAIL], fail_silently=False)
                messages.success(self.request, _("Email has been successfully sent."))
                return super(ContactFormView, self).form_valid(form)
        except Exception as e:
            messages.warning(self.request, _("Error trying to send email. If problem persists, please contact staff members."))
            return super(ContactFormView, self).form_invalid(form)

xb1/xb1/core/views.py
from django.conf import settings
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils import translation
from django.utils.translation import LANGUAGE_SESSION_KEY
from django.views.generic import View, RedirectView

from .forms import UserLoginForm
from .. import settings


class LoginMixinView(View):
    """
    Adds login form to context data.
    (Every site, which has login form must inherit this view)
    """

    def get_context_data(self, *args, **kwargs):

        context = super(LoginMixinView, self).get_context_data(*args, **kwargs)

        context["login_form"] = UserLoginForm

        return context


class SwitchLanguageRedirectView(RedirectView):

    def get_redirect_url(self, *args, **kwargs):

        if hasattr(self.request, "session"):
            session_language = self.request.session.get(LANGUAGE_SESSION_KEY, None)

            if session_language == "en":
                self.request.session[LANGUAGE_SESSION_KEY] = "cs"
            else:
                self.request.session[LANGUAGE_SESSION_KEY] = "en"
            self.request.session.save()

            translation.activate(self.request.session[LANGUAGE_SESSION_KEY])

        print(self.request.session[LANGUAGE_SESSION_KEY])

        return reverse_lazy("index")

xb1/xb1/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html>


  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static 'js/loading.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/loading.css' %}" />
    <link rel="stylesheet" href="{% static 'css/login.css' %}" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}" />
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}" />
    <link rel="stylesheet" href="{% static 'css/logo.css' %}" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
    {% block include %}{% endblock %}
  </head>

  <body>

     <!-- Loading animation during slow connection -->
    <div id="loading"></div>

    <!-- Modal login form -->
    <div id="login_modal" class="modal">
      <div class="modal_content">
        <span class="close">&times;</span>

        {% block modal %}

        <h1>{% trans "Login" %}</h1>

        <form id="login_form" method = "POST">
            {% csrf_token %}
            

            {{ login_form.username }}
            {{ login_form.password }}
            <a href="{% url 'password_reset' %}" class = "password_reset">{% trans "Forgotten password" %}</a>
            <br>
            <br>

            <button type = "submit">{% trans "Login" %}</button>
            <a id="sign_up" href = "{% url 'register' %}">{% trans "Sign Up" %}</a>

            
        </form>
        <div id="login_warning"></div>

        {% endblock %}
        
      </div>
    </div>

    {% block sidebar %}
    <!-- Left sidebar -->
    <div class="sidebar">
        <!-- Top sidebar options -->
        <ul class="sidebar-options">
            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'profile' %}"><i class="fas fa-user sidebarOffset"></i> {% trans "Profile" %}</a>
            </li>
            {% else %}
            <li>
                <a onclick="openDialog()"><i class="fas fa-user sidebarOffset"></i> {% trans "Profile" %}</a>
            </li>
            {% endif %}

            {% if perms.shop.view_order %}
                <li>
                    <a href="{% url 'shop:adminOrderList' %}"><i class="fas fa-shopping-basket sidebarOffset"></i>{% trans "Orders" %}</a>
                </li>
            {% elif user.is_authenticated %}
                <li>
                    <a href="{% url 'shop:userOrderList' %}"><i class="fas fa-shopping-basket sidebarOffset"></i>{% trans "Orders" %}</a>
                </li>
            {% endif %}

            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'contact:contact' %}"><i class="fas fa-envelope sidebarOffset"></i>{% trans "Contact" %}</a>
            </li>
            {% else %}
            <li>
                <a onclick="openDialog()"><i class="fas fa-envelope sidebarOffset"></i>{% trans "Contact" %}</a>
            </li>
            {% endif %}

        </ul>

        <!-- Bottom sidebar options -->
        <ul class="sidebar-options bottom">

            {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'logout' %}"><i class="fas fa-power-off sidebarOffset"></i>{% trans "Logout" %}</a>
                </li>
            {% endif %}
        </ul>
    </div>
    {% endblock %}


    {% block topnav %}
    <!-- Top navbar -->
    <nav class="navigation_bar navbar-fixed-top">
        <!-- Options -->
        <ul>
            {% if not user.is_authenticated %}
            <li><a class="login_trigger" onclick="openDialog()">{% trans "Log in" %}</a></li>
            {% endif %}

            {% if user.is_authenticated %}
                <li>
                    <div id="profile-dropdown" class="collapsed">
                        <img src="{{ user.profile.image.url }}" alt="profile photo">
                        <span>{{ user.username }} &#9660</span>
                        
                        <ul>
                            <li>
                                <a href="{% url 'profile' %}">{% trans "Profile" %}</a>
                            </li>
                            <li>
                                <a href="{% url 'logout' %}">{% trans "Logout" %}</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li><a href="{% url 'contact:contact' %}">{% trans "Contact" %}</a></li>
            {% else %}
                <li><a href="{% url 'contact:contact' %}">{% trans "Contact" %}</a></li>
            {% endif %}

            <li><a href="{% url 'shop:shopView' %}">{% trans "Eshop" %}</a></li>
            <li><a href="{% url 'articles:article_list' %}">{% trans "Articles" %}</a></li>
            <!-- <li><a href="#">{% trans "About us" %}</a></li> -->
            <li><a href="{% url 'forum:index' %}">{% trans "Forum" %}</a></li>
            {% if user.is_superuser %}
                <li><a href="/admin/">{% trans "Admin" %}</a></li>
            {% endif %}
            {% if perms.core.view_user %}
                <li><a href="{% url 'user_list' %}">{% trans "User list" %}</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endblock %}
    
      <!-- Success message content -->
     {% if message %}
     <div class="alert alert-warning">{{ message }}</div>
     {% endif %}

     {% for message in messages %}
     <div class="alert alert-{{message.tags}}" id="hideMe" >{{ message }}</div>
     {% endfor %}

    <div id="wrapper">
      <!-- Page content -->
      <div class="content">
          <!-- Header -->
          <div class="header">
              <!-- Logo -->
              <a href="{% url 'index' %}">
                  <img id="logo" src="{% static 'img/logo.png' %}"/>
              </a>
          </div>
          {% block content %} {% endblock %}
      </div>

      <!-- Scripts -->
      <script>
            $(function () {
              $(document).scroll(function () {
                  var $nav = $(".navbar-fixed-top");
                  $nav.toggleClass('scrolled', $(this).scrollTop() > $nav.height());
                });
            });

            $("#profile-dropdown").click(function() {
                $(this).toggleClass("collapsed")
            })
      </script>
      <script>
            $(document).on({
                ajaxStart: function() {
                    $('#wrapper').css('filter', 'blur(10px)');
                    $('#loading').css('visibility', 'visible');
                    $('#loading').css('display', 'block');
            },
                ajaxStop: function() {
                    $('#wrapper').css('filter', 'blur(0)');
                    $('#loading').css('visibility', 'hidden');
                    $('#loading').css('display', 'none');
            }
            });
      </script>

      {% if not user.is_authenticated %}
      <!-- Display warning if user fails to authenticate -->
      <script>
          document.getElementById("login_form").onsubmit = function(event) {
              event.preventDefault();
              $.ajax({
                  type:'POST',
                  async: true,
                  cache: false,
                  url:'{% url "login_modal" %}',
                  dataType: "json",
                  data: {
                      csrfmiddlewaretoken: $("#login_form input[type='hidden']").val(),
                      username: $("#login_form input[type='text']").val(),
                      password: $("#login_form input[type='password']").val()
                    },
                    // refresh on success
                    success: function(data) {
                        location.reload(true);
                    },
                    // display warning message
                    error: function(data) {
                        var warning = $("#login_warning")
                        warning.css("opacity", 1);
                        warning.empty().append('<p>' +  data.responseJSON.error + '</p>')

                    }
                });
            }
        </script>
        {% endif %}
        <script src="{% static 'js/login.js' %}"></script>
    </div>
  </body>
</html>

xb1/xb1/templates/base_no_nav.html
{% extends 'base.html' %}
{% block topnav %}{% endblock %}
{% block sidebar %}{% endblock %}

xb1/xb1/templates/index.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block include %}
<link rel="stylesheet" href="{% static 'css/layout1.css' %}" >
{% endblock %}

{%block content %}
  <div class="right">
    <div class="article_previews">
        {% for article in object_list %}
        {% if article.article_state == 1 %}
        <div class="preview">
          <div class="preview_title">
            <a href = "{% url 'articles:detail' slug=article.slug %}">
              {{ article.title }}
            </a>
          </div>
          <div class="preview_header">
            <img src="{{article.author.profile.image.url}}">
            <div class="preview_author_info">
              <div class="preview_author">{{article.author.profile.nickname}}</div>
              <div class="preview_date">{{article.modified}}</div>
            </div>
            {%if perms.articles.change_article %}
            <div class="preview_edit_button">
              <a href="{% url 'articles:article_update' pk=article.pk %}">
                {%trans "Edit"%}
              </a>
            </div>
            {%endif%}
          </div>
          <a href = "{% url 'articles:detail' slug=article.slug %}">
            <div class="preview_content">
              {% if article.thumbnail %}
              <div class="preview_thumb">
                <img src="{{article.thumbnail.url}}">
              </div>
              {%endif%}

              <div class="preview_text">
                {{ article.preview_text | safe | default_if_none:"" }}<br>
              </div>
            </div>
          </a>
        </div>
        {%endif%}
        {% empty %}
          {% trans "No articles created." %}
        {% endfor %}
      </div>
  </div>



  <div class="left">
    {% for article in object_list %}
      {%if forloop.first %}
        <h1>{{ article.title }}</h1><br>
        <p>{{ article.text | safe}}</p><br>
        <h3>{{ article.author.label }} {{ article.author }}</h3>
      {% endif %}

        {% empty %}
        <h1>{% trans "No articles created." %}</h1>
    {% endfor %}
  </div>
{% endblock %}